import { Poppins } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import "remixicon/fonts/remixicon.css";
import ServicesSection from "@/components/Service";
import Pricing from "@/components/Pricing";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata = {
  title: "Reza | Company Profile",
  description: "Generated by Mohammad Reza",
  icons: {
    icon: "/icon.jpg",
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="scroll-smooth">
      <body
        className={`${poppins.className} bg-[#e1e8e8] antialiased relative overflow-x-hidden`}
      >
        <div className="absolute top-[-20%] left-[-20%] w-[40vw] h-[40vw] bg-purple-300 rounded-full filter blur-3xl opacity-40"></div>

        <Navbar />
        <div className="container mx-auto px-5">{children}</div>
      </body>
    </html>
  );
}
